### ISSUE TITLE
Caught an exception in the keymap.

### ISSUE THREAD

**Issue by Ismael-VC** [KristofferC/PimpMyREPL.jl#11]
To reproduce, type something and then move the cursor to the beginning of the line and then type backspace:

```julia
julia> 1 + 1
       ^----cursor is here (now type backspace)
   
julia> WARNING: Caught an exception in the keymap:
ERROR: BoundsError: attempt to access 5-element Array{UInt8,1} at index [0]
2
```

Notice it does return the result (but I never press ENTER).

**Comment by KristofferC** [comment]
Thanks for report, Fixed by https://github.com/KristofferC/PimpMyREPL.jl/commit/a66f78aef3bb3399b7b20ea36b8c83e8b523721d
