### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by rsrock** [KristofferC/PimpMyREPL.jl#12]
This error comes and goes.  If I bump up the `sleep` to `sleep(0.3)`, this seems to go away.  Perhaps that's the easiest fix?

```
ERROR (unhandled task failure): LoadError: LoadError: UndefRefError: access to undefined reference
 in insert_into_keymap() at /Users/rrock/.julia/v0.5/PimpMyREPL/src/bracket_inserter.jl:38
 in include_from_node1(::String) at ./loading.jl:426 (repeats 2 times)
 in eval(::Module, ::Any) at ./boot.jl:234
 in require(::Symbol) at ./loading.jl:357
 in eval(::Module, ::Any) at ./boot.jl:234
 in macro expansion at /Users/rrock/.juliarc.jl:19 [inlined]
 in (::##4#6)() at ./task.jl:360
while loading /Users/rrock/.julia/v0.5/PimpMyREPL/src/bracket_inserter.jl, in expression starting on line 106
while loading /Users/rrock/.julia/v0.5/PimpMyREPL/src/PimpMyREPL.jl, in expression starting on line 19
```

I'm on OS X using iTerm2

**Comment by KristofferC** [comment]
Interesting. I guess that would happen if I try to inject into the prompts keymap before it has been created. Long term I should probably create a completely separate prompt and swap out the original julia prompt for that one. Short tem, either detecting when the keymap is created or have a short sleep after detecting that the REPL is active should fix it.

**Comment by KristofferC** [comment]
Since I can not reproduce this. Could you try adding a `sleep(0.05)` before the `@eval using PimpMyREPL` and see if that fixes things?

**Comment by rsrock** [comment]
It does seem to fix it.  Even a `sleep(0.001)` works in that spot, with the original `sleep(0.1)` in the `else`.

**Comment by KristofferC** [comment]
I updated the README. Thanks for the report.
