### ISSUE TITLE
Known bugs

### ISSUE THREAD

**Issue by KristofferC** [KristofferC/PimpMyREPL.jl#3]
### Fixed:
- [x] Pressing up arrow twice does not reapply the passes. Likely some state change in the REPL code that is not hooked into. Edit: Yep,  it swaps to a `PrefixHistoryPrompt` after up arrow. [Fixed by https://github.com/KristofferC/PimpMyREPL.jl/pull/16]
- [x] Writing `1+1` hides everyhing after the `+`. `1 + 1` works. [Fixed by https://github.com/KristofferC/Tokenize.jl/commit/51c006d4108d30c5b787a4b7140195ce62a59276]
- [x] Bracket pasting multiple statement sometimes freezes the REPL. [Fixed by https://github.com/KristofferC/PimpMyREPL.jl/commit/6870958d86778306932f8f23c939362f7480211b]
- [x] Entering something in help REPL and then pressing up should write help REPL prompt [Fixed by
https://github.com/KristofferC/PimpMyREPL.jl/commit/d6b0f3163a4f0e67c4b824794e9c2cc9defe72ad]
- [x] Backarrow on a unicode char throws. [Fixed by https://github.com/KristofferC/PimpMyREPL.jl/commit/ce3c40b37a33ed79b4b05c58672d25faf04cb55e]
- [x] Prompt pasting does not seem to work on windows. [Won't fix, no way to detect a paste is occuring on windows cmd]

**Comment by Ismael-VC** [comment]
I think you can now move the first active, to the fixed list.

**Comment by KristofferC** [comment]
Indeed, thanks.
