### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by KristofferC** [KristofferC/PimpMyREPL.jl#6]
- [x] enable support for 256 color terminals [Fixed by https://github.com/KristofferC/PimpMyREPL.jl/commit/dd0ee31cb1cdd1870afe03ddb65a7e14f64480f1]
- [x] Fix precompilation, it is currently slow enough to load that it is annoying. Precompilation might help.
- [x] Second step, get working with `userimg.jl`

**Comment by fredrikekre** [comment]
- [ ] Add automatic indentation (?)

**Comment by KristofferC** [comment]
Yes, I don't have a good system in place right now for modifying the size of the input buffer but it should not be too difficult. Sublime has something like this so I would probably just copy their behavior.

**Comment by Ismael-VC** [comment]
[ x ] Fix precompilation

**Comment by KristofferC** [comment]
`userimg.jl` now works and is documented
