### ISSUE TITLE
turning off bracket matching

### ISSUE THREAD

**Issue by EthanAnderes** [KristofferC/PimpMyREPL.jl#7]
Started using this...loving it so far. However, I would like to be able to turn off the bracket matching.
I'm not an expert on how to set up this sort of thing, but adding the following function `bracket_inserter` to the source code seems to get what I want (but with a redefining constant warning).

```julia
const BRACKET_INSERTER = BracketInserter(true)
function bracket_inserter(b::Bool)
    global BRACKET_INSERTER = BracketInserter(b)
end
```

Can something like this be added to the source code, so I don't have to locally modify the source?

**Comment by KristofferC** [comment]
Yes, I will fix it. Thanks for the comment.

**Comment by KristofferC** [comment]
Ok, `enable_autocomplete_brackets(::Bool)` lets you turn on and off

**Comment by niczky12** [comment]
I know this is very stale, but it is not obvious to me how I would use this setting. The auto-brackets thing doesn't play nicely with vscode's send to terminal feature.

**Comment by KristofferC** [comment]
You woul call `enable_autocomplete_brackets(false)`
