### ISSUE TITLE
Turning off syntax highlighting

### ISSUE THREAD

**Issue by okvs** [KristofferC/PimpMyREPL.jl#8]
It would be good if the documentation would show how to disable syntax highlighting:
```
colorscheme!("Default")
```
Highlighting is great, but unfortunately Monokai seems best suited to dark terminal themes, and less so for light ones.

It is also slightly confusing that highlighting 'on' is the default, while the black-and-white theme is called `Default`.

(As an added bonus, perhaps two functions `colorscheme` and `colorschemes` (without input args) could return the active and the available colorschemes, respectively?)

**Comment by KristofferC** [comment]
Yes, I thought about this too. Will add something tonight.

**Comment by okvs** [comment]
Actually, I just realized that even with the `"Default"` setting there are still some changes, such as non-bold input letters. Maybe a colorscheme that reverts to standard settings completely would be an idea.

**Comment by KristofferC** [comment]
Yes, that was my plan.

**Comment by KristofferC** [comment]
The colorscheme "JuliaDefault" now is bold and the default color so should be like the normal julia scheme.

**Comment by KristofferC** [comment]
If you have a better colorscheme for light terminals it should be fairly easy to create one by looking at the code for how the monokai are made.
