### ISSUE TITLE
Spell check idea

### ISSUE THREAD

**Issue by PallHaraldsson** [KristofferC/PimpMyREPL.jl#9]
I had a thought, since I've been fixing spelling in some packages for people.. Why not for source code (I wasn't sure if it was done in IDEs), and found out it's done:

https://github.com/myint/scspell

That's only for Python, I also found an Atom issue (closed, not sure if it's done, then maybe only for HTML, Markdown etc.).

Since spelling isn't about Julia (vs. Python) keywords (and they are English anyway), maybe the code above could be reused.

Ideally I would not just want it in the REPL (but so far the only thing I use..). Would you think it should be a separate package (maybe REQUIREd from this one and from Juno/Atom.. etc. Not sure if that is possible Atom written in non-Julia, right?)?

**Comment by PallHaraldsson** [comment]
If you do take this seriously, then multi-language spell-check would be nice.. Not just for your Swedish, but also for my Icelandic.. in addition to a main language, English.

[Since spellcheck for Icelandic is non-trivial (word lists are not ideal, but I believe done, but also special purpose Icelandic spell check software, only non-free software that I'm aware of, unlike the former), you may not want to think too much about that, just assume dual word-lists ok..]

**Comment by KristofferC** [comment]
I think I do not want spell check in this package.  I don't see much point in it since the REPL is basically only used for things that will not be reused. Real code is written in a text editor and there you have spell checks anyway.
